---
- hosts: app_servers
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Copy website files
      copy:
        src: /home/ubuntu/index.html
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
